### ISSUE TITLE
Unhandled promise rejections error

### ISSUE THREAD

**Issue by PixelT** [mrmlnc/vscode-scss#70] opened 2018-05-19 22:39 UTC
I have an error in output console:
```
[Error - 00:36:19] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '{here-path-to-file-url}'
[Error - 00:36:19] (node:21072) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by PixelT** [comment] 2018-06-07 08:46
@mrmlnc can you do something with this? It's annoying because the output window is shown repeatedly, even if I close it...

**Comment by raldred** [comment] 2018-06-29 09:29
dupe of #67

**Comment by marcelomgarcia** [comment] 2019-01-28 12:00
I got this error today:
=== cut here ===
[Error - 12:56:33 PM] (node:9136) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): #<Object>
[Error - 12:56:33 PM] (node:9136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 12:56:33 PM] (node:9136) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): #<Object>
=== cut here ===

It appeared after I added a folder to my workspace, as suggested in the documentation:
https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by inversiondk** [comment] 2019-03-02 23:50
I'm also getting this error: 
![image](https://user-images.githubusercontent.com/12465718/53689102-3bb56d80-3d4e-11e9-9da6-a46ad4454a72.png)

I can't use intellisense for any variables. However - after some time some variables show up - but not all. 
Restarting VScode doesn't seem to help. 

Any chance of fixing this as the extension is great?

**Comment by octref** [comment] 2019-11-13 17:01
#75 should at least hide the error.

**Closed by octref** 2019-11-13 17:01 UTC
