### ISSUE TITLE
Feature: color preview

### ISSUE THREAD

**Issue by PixelT** [mrmlnc/vscode-scss#57] opened 2017-12-01 08:07 UTC
Add a small square with color value into suggest list.

Instead of this:

![](https://i.imgur.com/EXO6xCM.png)

this:

![](https://i.imgur.com/Um0Pcuj.png)

**Comment by mrmlnc** [comment] 2017-12-01 08:09
Duplicate of https://github.com/mrmlnc/vscode-scss/issues/13.

**Closed by mrmlnc** 2017-12-01 08:09 UTC
