### ISSUE TITLE
No varaibel suggestions with partaials

### ISSUE THREAD

**Issue by packytagliaferro** [mrmlnc/vscode-scss#51] opened 2017-08-10 03:52 UTC
I have my scss set up like so:

```
Base
   |->_variables.scss
Layouts
   |->_header.scss
App.scss
```

App.scss
```
@import "base/variables";
@import "layouts/header";
```

variables.scss
`$color-primary: black;`

Now in `header.scss` if I start typing `$colo` I get nothing. No hint to use `$color-primary`

Is there something I am missing?

**Comment by TzviCons** [comment] 2017-09-06 19:43
I believe this is handled in #49 and fixed in pre-release 0.7.0

**Comment by octref** [comment] 2019-11-12 19:41
Duplicate of #49.

**Closed by octref** 2019-11-12 19:41 UTC
Labels: Priority: Low, Type: Bug
