### ISSUE TITLE
Extension reports 2 errors

### ISSUE THREAD

**Issue by pdemilly** [mrmlnc/vscode-scss#76] opened 2018-10-10 21:49 UTC
- Extension Name: vscode-scss
- Extension Version: 0.6.2
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 107,
		"activateCallTime": 17,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:scss"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		},
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		}
	]
}
```

**Comment by octref** [comment] 2019-11-12 19:17
Duplicate of #69.

**Closed by octref** 2019-11-12 19:17 UTC
