### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by 7iomka** [mrmlnc/vscode-scss#81] opened 2019-09-18 00:06 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-scss`
- Extension Version: `0.6.2`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 28,
		"activateCallTime": 4,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:scss"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		}
	]
}
```

**Comment by octref** [comment] 2019-11-12 19:17
Duplicate of #69.

**Closed by octref** 2019-11-12 19:17 UTC
Labels: Type: Duplicate
